[2025-03-18 11:43:39,420] 97 werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://192.168.0.103:5000
[2025-03-18 11:43:39,422] 97 werkzeug - INFO - [33mPress CTRL+C to quit[0m
[2025-03-18 11:43:44,109] 97 werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 11:43:44] "GET /predict HTTP/1.1" 200 -
[2025-03-18 11:43:44,241] 97 werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 11:43:44] "[36mGET /static/stylesheets/style.css HTTP/1.1[0m" 304 -
[2025-03-18 11:43:49,731] 97 werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 11:43:49] "GET / HTTP/1.1" 200 -
[2025-03-18 11:43:49,749] 97 werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 11:43:49] "[36mGET /static/stylesheets/index.css HTTP/1.1[0m" 304 -
[2025-03-18 11:43:54,623] 97 werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 11:43:54] "GET /predict HTTP/1.1" 200 -
[2025-03-18 11:43:54,667] 97 werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 11:43:54] "[36mGET /static/stylesheets/style.css HTTP/1.1[0m" 304 -
[2025-03-18 11:44:11,970] 66 root - INFO - Datafram Gathered
[2025-03-18 11:44:14,081] 875 application - ERROR - Exception on /predict [POST]
Traceback (most recent call last):
  File "D:\Git\Diamond Price Prediction\src\pipeline\prediction_pipeline.py", line 22, in predict
    pred = model.predict(data_scaled)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\Diamond Price Prediction\venv\Lib\site-packages\sklearn\tree\_classes.py", line 530, in predict
    X = self._validate_X_predict(X, check_input)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\Diamond Price Prediction\venv\Lib\site-packages\sklearn\tree\_classes.py", line 485, in _validate_X_predict
    if self._support_missing_values(X):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\Diamond Price Prediction\venv\Lib\site-packages\sklearn\tree\_classes.py", line 188, in _support_missing_values
    and self.monotonic_cst is None
        ^^^^^^^^^^^^^^^^^^
AttributeError: 'DecisionTreeRegressor' object has no attribute 'monotonic_cst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Git\Diamond Price Prediction\venv\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\Diamond Price Prediction\venv\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\Diamond Price Prediction\venv\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\Diamond Price Prediction\venv\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\Diamond Price Prediction\application.py", line 34, in predict_datapoint
    pred=predict_pipeline.predict(final_new_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Git\Diamond Price Prediction\src\pipeline\prediction_pipeline.py", line 27, in predict
    raise CustomException(e,sys)
src.exception.CustomException: Error occured in python script name [D:\Git\Diamond Price Prediction\src\pipeline\prediction_pipeline.py] line number [22] error message: ['DecisionTreeRegressor' object has no attribute 'monotonic_cst']
[2025-03-18 11:44:14,100] 97 werkzeug - INFO - 127.0.0.1 - - [18/Mar/2025 11:44:14] "[35m[1mPOST /predict HTTP/1.1[0m" 500 -
